In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./Sales_data_RMF.csv')

/tmp/ipykernel_31324/354546881.py:1: DtypeWarning: Columns (0,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./Sales_data_RMF.csv')

In [3]:
df

,주문번호,배송완료일,배송시작일,구매일,구매시월령,고객번호,구매금액,결제금액,물품대분류,상품명,포인트,배송준비시간,배송시간,물품중분류,물품소분류
0,901011864201303,2021-01-05,2021-01-01,2020-12-31,35,201901010750089,74560,43825,팬티,하기스 매직핏팬티 5단계 남아 124매(팬티형),30735,1 days,4 days,기저귀,팬티형
1,901011864430366,2021-01-03,2021-01-01,2020-12-31,9,201901010750143,74560,43825,팬티,하기스 매직핏팬티 3단계 남아 184매(팬티형),30735,1 days,2 days,기저귀,팬티형
2,81231186197954,2021-01-05,2021-01-01,2020-12-31,22,201812310749820,53920,36769,팬티,하기스 네이처메이드 팬티 5단계 여아 80매(팬티형),17151,1 days,4 days,기저귀,팬티형
3,812311863500220,2021-01-03,2021-01-01,2020-12-31,8,201812310750007,52160,32408,팬티,하기스 보송보송팬티 4단계 공용 124매(팬티형),19752,1 days,2 days,기저귀,팬티형
4,812311863220192,2021-01-03,2021-01-01,2020-12-31,23,201812310749977,47360,30066,팬티,하기스 에어솔솔 팬티 5단계 남아용 80매(팬티형),17294,1 days,2 days,기저귀,팬티형
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199994,00806233401-26770461124511,2022-08-11,2022-08-08,2022-08-07,13,201906180918504,21300,14910,FC,라네이처 시그니처 울트라슬림 날개 중형 12개입 (EA),6390,1 days,3 days,생리대,생리대
199995,00806204436-0461904922687,2022-08-11,2022-08-08,2022-08-07,163,201901280776735,7900,5840,FC,라네이처 시그니처 맥시슬림 날개 중형 12개입 (EA),2060,1 days,3 days,생리대,생리대
199996,00806204436-0461904922688,2022-08-12,2022-08-08,2022-08-07,163,201901280776735,7100,5240,FC,라네이처 시그니처 울트라슬림 날개 대형 10개입 (EA),1860,1 days,4 days,생리대,생리대
199997,00806215930-05281256126202,2022-08-10,2022-08-08,2022-08-07,5,201906200921415,7100,5240,FC,라네이처 시그니처 울트라슬림 날개 소형 14개입 (EA),1860,1 days,2 days,생리대,생리대
199998,00806233401-26770461124510,2022-08-10,2022-08-08,2022-08-07,13,201906180918504,5670,4190,FC,좋은느낌 유기농순면 뉴 맥시슬림 오버나이트 12개입 (EA),1480,1 days,2 days,생리대,생리대

In [10]:
df_4 = df[df['배송시간'] <= '4 days'] 
df_5 = df[df['배송시간']>= '5 days']

In [13]:
dup_cnt = df_4.groupby('고객번호')['구매일'].nunique()

# 새로운 데이터프레임 생성
new_df_4 = pd.DataFrame({
    '고객번호': dup_cnt.index,
    '구매횟수': dup_cnt.values
})

In [14]:
dup_cnt = df_5.groupby('고객번호')['구매일'].nunique()

# 새로운 데이터프레임 생성
new_df_5 = pd.DataFrame({
    '고객번호': dup_cnt.index,
    '구매횟수': dup_cnt.values
})

In [15]:
new_df_4

                       고객번호  구매횟수
0           201812310749770     1
1           201812310749771     1
2           201812310749774     2
3           201812310749780     1
4           201812310749783     4
...                     ...   ...
95267  20200724113017315991     1
95268  20200729134409126553     1
95269  20200803075905757887     1
95270  20200805170229147688     1
95271  20200805223526494551     1

[95272 rows x 2 columns]

In [17]:
new_df_5

                      고객번호  구매횟수
0          201812310749735     1
1          201812310749784     1
2          201812310749820     1
3          201812310749831     1
4          201812310749876     2
...                    ...   ...
7847       201912311058854     2
7848       201912311058941     1
7849  20200601135728421473     1
7850  20200608105302522972     1
7851  20200619005724926190     1

[7852 rows x 2 columns]

In [18]:
from scipy import stats

t_test1 = stats.ttest_ind(new_df_4['구매횟수'], new_df_5['구매횟수'])
print(t_test1)

Ttest_indResult(statistic=36.3795882940641, pvalue=6.0709074724039204e-288)

- pvalue 값 거의 0이므로 귀무가설 기각
- 따라서 배송시간(1~4, 5이상) 에 따른 재구매횟수의 차이가 있다